### ISSUE TITLE
(Question) how to switch between two example huds

### ISSUE THREAD

**Issue by AG4lyf** [dionpirotta/Custom-CSGO-HUD#11]
In the Example section (https://github.com/dionpirotta/Custom-CSGO-HUD#examples) There are 2 examples. The default is upper one how can i get the bottom one with stripes and all cuz that looks cool.

**Comment by dionpirotta** [comment]
The bottom one isnt available, was a quick 'you can program it to chwnge it like this.

However, the NEW system will feature a better HUD which I estimate will be about 2-3 weeks away

**Comment by AG4lyf** [comment]
Cool will wait for newer version

**Comment by SurajBhari** [comment]
Any Update on "NEW" system ? 
or was it a reference to https://github.com/lexogrine/hud-manager ?
