### ISSUE TITLE
Defusing & Planting Bomb Alerts

### ISSUE THREAD

**Issue by EmirBoyaci** [dionpirotta/Custom-CSGO-HUD#13]
Hello,

Defusing & planting bomb alerts doesn't work even though i didn't change anything from hud files. Can you help me to fix this? Is it working in your hud @dionpirotta ?

**Comment by dionpirotta** [comment]
Hi,

Should be working? Unless valve have changed something in the gamestate that I am unaware of?

Make sure you have setup everything correctly in the repository and follow all the steps.
