### ISSUE TITLE
HUD loads default example values

### ISSUE THREAD

**Issue by rvneXe** [dionpirotta/Custom-CSGO-HUD#27]
hi, I followed the tutorial step by step, and:
![Uploading Screenshot (104).png…]()

**Comment by rvneXe** [comment]
![Screenshot (104)](https://user-images.githubusercontent.com/89677246/203382748-cc528c4a-35c6-43c5-a5eb-b5c426fb5f8e.png)

**Comment by Definq** [comment]
same problem, the hud is just static, I don't understand how to synchronize it with the game
